# More info on config here: https://golangci-lint.run/usage/configuration/
run:
  deadline: 5m
  issues-exit-code: 1

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  sort-results: true

linters:
  enable:
    # enabled by default:
    - errcheck    # unchecked error values
    - gosimple    # simplifications
    - govet       # various items, see: https://pkg.go.dev/cmd/vet
    - ineffassign # detects unused assignments
    - staticcheck # some rules from staticcheck.io
    - typecheck   # typechecks code, like the compiler
    - unused      # checks for unused constants/variables/functions/types

    # explicitly enabled:
    - asciicheck       # all identifiers are ASCII
    - bidichk          # no Unicode bidi sequences as per CVE-2021-42574
    - bodyclose        # HTTP response bodies are closed
    - dupword          # things like 'the the' in comments/strings
    - durationcheck    # bad time.Duration arithmetic
    - errorlint        # common errors with Go 1.13+ error wrapping
    #- exhaustruct      # all struct fields are initialized
    - exportloopref    # escaping pointers to loop variables
    #- gci              # deterministic import ordering
    - gocritic         # lots of small checks, see <https://go-critic.com/overview>
    - noctx            # HTTP requests are passed a Context
    - nolintlint       # bad "nolint" directives
    - predeclared      # no identifiers in Go's list of predeclared identifiers, see <https://go.dev/ref/spec#Predeclared_identifiers>
    - unparam          # no unused function parameters or return values
