name: lints
on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          install-mode: 'binary'
          version: 'latest'
          skip-pkg-cache: true
          skip-build-cache: true

  check-go-mod-tidy:
    name: check go mod tidy
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: go mod tidy
        run: |
          go mod tidy
      - name: check diff
        run: |
          if ! (test -z "$(git ls-files --exclude-standard --others .)$(git diff .)"); then
            git ls-files --exclude-standard --others .
            git diff .
            echo "ERROR: 'go mod tidy' modified the source tree."
            exit 1
          fi

  codespell:
    name: check spelling with codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: codespell-project/actions-codespell@v2
        with:
          check_hidden: true
          skip: go.sum,.git
