name: release
on:
  push:
    tags:
      - "v*.*.*"

env:
  IMAGE: "neondatabase/aws-cost-reporter"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: get version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      -
        name: git checkout
        uses: actions/checkout@v3
      -
        name: login to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.NEON_DOCKERHUB_USERNAME }}
          password: ${{ secrets.NEON_DOCKERHUB_PASSWORD }}
      -
        name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.IMAGE }}:${{ steps.get_version.outputs.version }}
            ${{ env.IMAGE }}:latest
      -
        name: Release
        uses: softprops/action-gh-release@v1
